services:
  - type: web
    name: baccarat-h2o-ai
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: H2O_MAX_MEM
        value: 1G
      - key: H2O_MAX_MODELS
        value: "10"
      - key: H2O_MAX_RUNTIME_SECS
        value: "120"
